### ISSUE TITLE
I can't see the title/thumbnail changes I made myself

### ISSUE THREAD

**Issue by rom428** [ajayyy/DeArrow#211]
When I edit a title or a thumbnail, the original title/thumbnail still shows, but, when the change was made by someone else, the change shows to me.

Details: I'm using the extension Firefox nightly on Android.

**Comment by ajayyy** [comment]
Can you send an example?

**Comment by rom428** [comment]
The original title on the web browser
![Screenshot_2024-01-02-20-32-31-263_org mozilla fenix](https://github.com/ajayyy/DeArrow/assets/146016473/21955988-5313-4e31-a7dc-dd74a845914c)
The title I submitted (Here I'm using a Clipious account, it doesn't require to use a DeArrow account, so I'm not logged in)
![Screenshot_2024-01-02-20-32-58-243_com github lamarios clipious](https://github.com/ajayyy/DeArrow/assets/146016473/fc88678c-501e-4e86-b8b3-b2ec951e2ecf)
Here you can see that if another user submitted a title, it'll appear as usually.
![Uploading Screenshot_2024-01-02-20-33-29-751_org.mozilla.fenix.png…]()

**Comment by ajayyy** [comment]
If you submit on the same device/extension, it will save your personal submissions to show you always, but in your case that is not happening since you are submitting from Clipious.

By default, submitted titles are not shown to everyone until your account gets flagged as "verified". This occurs when someone else goes to the video, opens the voting menu, and upvotes at least one of your titles. Once that happens, all your titles will appear to everyone.
