### ISSUE TITLE
option to add the channel name to the title

### ISSUE THREAD

**Issue by mortee** [ajayyy/DeArrow#297]
I've been struggling with bookmarked videos not having any channel info on the bookmark, only the title. I've been looking for a solution when I came across this extension. 

While it's a really useful tool, it doesn't address what's been my problem in the first place.

So, what about an option to append the channel name to the title? Or maybe allowing the user to specify a custom title template, with % placeholders or similar provided with various bits of info about the video?

**Comment by LWChris** [comment]
I don't think DeArrow is meant to be used as a YouTube customizer. You can let it alter the casing of existing titles to your liking, but I don't think it's in-scope to have it build personalized title templates.

If I understand correctly, when you're talking about "bookmark" you are talking about the normal browser feature, not a YouTube feature, right? Because then I'd suggest you "just" add the name of the channel during bookmarking?

Otherwise, I feel like this would be a perfect request for a userscript or the "Improve YouTube" extension.

**Comment by mortee** [comment]
You're right, since posting this issue, I've been looking around further, and I realized that there's [really good user scripts](https://greasyfork.org/en/scripts/450646-youtube-better-window-title) for this.
