### ISSUE TITLE
Automatic capitalization: issues with unicode

### ISSUE THREAD

**Issue by KMikeeU** [ajayyy/DeArrow#32]
Automatic capitalization sometimes generates odd titles when the first letter is a unicode character

Original title:
`Ski Aggu über Crazy Frog, "Party Sahne", Southstar & Domiziana – Interview mit Aria Nejati`

Auto generated:
`Ski Aggu üBer Crazy Frog, "Party Sahne", Southstar & Domiziana – Interview Mit Aria Nejati`

The issue being the capital B in "über"

**Comment by ajayyy** [comment]
Should be fixable by changing the "is letter" check to include unicode letters. The reason for it is to exclude quotes, or brackets, etc.

Also auto-caps is going to be disabled in next version if the main language is not english since many expressed concern that the title case rules don't apply in other languages. Will have to determine a good solution for that long term.
