### ISSUE TITLE
Confusing Extention Model

### ISSUE THREAD

**Issue by TroubledPerson** [ajayyy/DeArrow#87]
according to the see details it says this "When it exits beta, new users will have to pay to use the extension, or request free access through an alternative process.". it doesn't make sense as this is an open source extension as the source code is distributed. as said here "the extension code will still be open source". thus monetizing the extension would not be possible as someone can get around this extension paywall by downloading the source code and compiling the code themselves or even, someone forks the code under a new name and people install that instead. maybe should it say soft-paywall for priority access? as that would be easier to monetize if it were on the server end rather than client.

P.S love this project! it is awesome and hope all goes well.

**Comment by ajayyy** [comment]
If you want some examples of open source projects with license key systems see Cryptomator for Android (which is on Fdroid, but requires a license key to activate), and Ardour

I don't want to have restrict access on the server end, because I want other ports to be able to use it for free (like NewPipe, vanced etc).

But I get the concern! I guess I'll see how things go.

**Comment by TroubledPerson** [comment]
ok thanks for clarification
